name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y \
          python3 python3-pip python3-setuptools git zip \
          libffi-dev libssl-dev libglu1-mesa-dev pkg-config \
          libgl1-mesa-dev libegl1-mesa-dev \
          openjdk-17-jdk unzip

    - name: Install buildozer & Cython
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Prepare Android SDK manually
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip
        mv cmdline-tools latest

    - name: Accept licenses
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install build-tools + platforms
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;36.1.0" "platforms;android-34"

    - name: Set ANDROID_HOME for Buildozer
      run: echo "export ANDROID_HOME=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV

    - name: Build APK
      run: |
        export ANDROID_HOME=${{ github.workspace }}/android-sdk
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
